// seedSkills.js
const Skill = require('../models/mysql/skill.model');

const seedSkills = async () => {
    const skills = [
        { name: "Ensamble del sistema ", operation_id: 1 },
        { name: "Soldadura brazing ", operation_id: 9 },
        { name: "Soldadura estaño ", operation_id: 11 },
        { name: "GP12", operation_id: 13 },
        { name: "Packing nut", operation_id: 6 },
        { name: "Torque adapter", operation_id: 5 },
        { name: "GP12", operation_id: 8 },
        { name: "Filter pack ", operation_id: 21 },
        { name: "BRANSON ", operation_id: 23 },
        { name: "Maquina CNC ", operation_id: 17 },
        { name: "Corte de ceja, lijado y assy de clapper ", operation_id: 19 },
        { name: "Resorte, ensamble de válvula ", operation_id: 20 },
        { name: "EMPAQUE", operation_id: 18 },
        { name: "Handle", operation_id: 3 },
        { name: "Prueba de fuga ", operation_id: 4 },
        { name: "Marcado", operation_id: 7 },
        { name: "Ensamble de steam", operation_id: 2 },
        { name: "INSERCION DE O-RING ", operation_id: 2 },
        { name: "INSERCION DE SEAT ", operation_id: 2 },
        { name: "INSERCION DE SEAT ", operation_id: 2 },
        { name: "KITS ", operation_id: 23 },
        { name: "KITTEO ", operation_id: 14 },
        { name: "Corte de manguera", operation_id: 15 },
        { name: "Teflonera", operation_id: 14 },
        { name: "Corte de flow restrictor ", operation_id: 14 },
        { name: "ENSAMBLE DE BUSHING Y ROLLER ", operation_id: 19 },
        { name: "Prueba de fuga ", operation_id: 48 },
        { name: "Ensamble de bushing y roller ", operation_id: 18 },
        { name: "Prueba de fuga minifold", operation_id: 25 },
        { name: "ENSAMBLE Y EMPAQUE MANIFOLD ", operation_id: 25 },
        { name: "Set up (arranque, purga)", operation_id: 26 },
        { name: "REBABEO", operation_id: 28 },
        { name: "Ensamble y empaque manifold", operation_id: 25 },
        { name: "Ensamble, empaque de varilla ", operation_id: 36 },
        { name: "Perforación de tornillo ", operation_id: 36 },
        { name: "Sub-ensamble de gasket a pin ", operation_id: 36 },
        { name: "Ensamble de cadenas ", operation_id: 36 },
        { name: "Empaque y reempaque de flotador ", operation_id: 36 },
        { name: "Etiquetado en general ", operation_id: 36 },
        { name: "Ensamble brazos de válvula ", operation_id: 36 },
        { name: "Ensamble, empaque y válvulas flippen ", operation_id: 36 },
        { name: "Ensamble de adaptador ", operation_id: 36 },
        { name: "Ensamble de varilla a flotador ", operation_id: 36 },
        { name: "Ensamble de gasket a flotador ", operation_id: 24 },
        { name: "Empaque 288", operation_id: 24 },
        { name: "ENSAMBLE DE O-RING EN BONNET ", operation_id: 24 },
        { name: "ENSAMBLE ESTAMPA EN PLACA ", operation_id: 24 },
        { name: "PRUEBA DE FUGA 288", operation_id: 24 },
        { name: "Lectura de dibujos ", operation_id: 25 },
        { name: "Uso moldeadora ", operation_id: 26 },
        { name: "Empaque moldeo ", operation_id: 26 },
        { name: "Mezcla de resina con colorante", operation_id: 26 },
        { name: "Ensamble moldeo ", operation_id: 26 },
        { name: "Etiquetado moldeo ", operation_id: 26 },
        { name: "Procedimiento para regrind", operation_id: 26 },
        { name: "Rebabeo ", operation_id: 26 },
        { name: "LECTURA DE DIBUJOS ", operation_id: 28 },
        { name: "MEDICION CON VERNIER ", operation_id: 28 },
        { name: "MEDICION CON CINTA PI", operation_id: 28 },
        { name: "Ensamble manual ", operation_id: 38 },
        { name: "ENSAMBLE SEMIAUTOMATICO ", operation_id: 38 },
        { name: "ENSAMBLE AUTOMATICO ", operation_id: 38 },
        { name: "Empaque maquinado bagger 1 ", operation_id: 39 },
        { name: "Empaque general manifold", operation_id: 39 },
        { name: "Empaque manual ", operation_id: 39 },
        { name: "Ensamble supercoil", operation_id: 40 },
        { name: "Prueba de fuga, mangueras ", operation_id: 40 },
        { name: "Soldadura de balt valve", operation_id: 40 },
        { name: "Empaque de maquina", operation_id: 40 },
        { name: "Remachado conector de manguera ", operation_id: 40 },
        { name: "Corte de manguera ", operation_id: 40 },
        { name: "Operación de maquina taper 1 y 2", operation_id: 42 },
        { name: "Operación de spool machine ", operation_id: 42 },
        { name: "Corte de tapete mat", operation_id: 42 },
        { name: "Elaboración de cold lead ", operation_id: 42 },
        { name: "ESTAÑADO SOLDADURA RADIANT ", operation_id: 41 },
        { name: "Splice de soldadura por calor ", operation_id: 41 },
        { name: "DESPOJE MECANICO/TERMICO ", operation_id: 41 },
        { name: "Remachado de splice", operation_id: 43 },
        { name: "Despoje mecánico térmico", operation_id: 43 },
        { name: "Soldadura sonic welder/electric mat", operation_id: 43 },
        { name: "Reducción de tubing", operation_id: 44 },
        { name: "Prueba eléctrica radiant ", operation_id: 45 },
        { name: "Empaque warm wire y mat (tapete)", operation_id: 45 },
        { name: "Corte de pin y empaque", operation_id: 48 },
        { name: "Empaque en maquina ", operation_id: 40 },
        { name: "REMACHADO CONECTOR DE MANGUERA ", operation_id: 40 },
        { name: "CORTE DE MANGUERA", operation_id: 40 },
        { name: "Empaque de bolsas", operation_id: 38 },
        { name: "Empaque a granel ", operation_id: 38 },
        { name: "PRUEBA DE FUGA ", operation_id: 38 },
        { name: "Preparación y ensamble para brazing ", operation_id: 9 },
        { name: "Preparación y ensamble para estaño", operation_id: 11 },
        { name: "Prueba de fuga", operation_id: 12 },
        { name: "Enderezado de lámina (hammer)", operation_id: 49 },
        { name: "Set up máquina de corte (laminas)", operation_id: 49 },
        { name: "Corte espaciador", operation_id: 49 },
        { name: "Perforado de lámina y espaciador ", operation_id: 49 },
        { name: "Ensamble inner, tornillos, tuercas ", operation_id: 49 },
        { name: "Ensamble del diafragma 7,8 y 9", operation_id: 37 },
        { name: "Insertado de O-ring 7,8 y 9", operation_id: 37 },
        { name: "Ensamble diafragma de 8 automático ", operation_id: 37 },
        { name: "Ensamble y empaque 8 automático ", operation_id: 37 },
        { name: "Ensamble y empaque 7,8 y 9", operation_id: 37 },
        { name: "Prueba de fuga", operation_id: 37 },
        { name: "MAQUINADOS ", operation_id: 52 },
        { name: "Kanban Tag handle ", operation_id: 53 },
        { name: "ALMACEN ", operation_id: 54 },
        { name: "EMBARQUES ", operation_id: 55 },
        { name: "MEDICION CON VERNIER ", operation_id: 56 },
        { name: "MEDICION CON CINTA PI ", operation_id: 56 },
        { name: "MEDICION CON MALTIMETRO", operation_id: 56 },
        { name: "INTERPRETACION DE DIBUJOS ", operation_id: 57 },
        { name: "INTERPRETACION DE BOM ", operation_id: 57 },
        { name: "CTQ's", operation_id: 57 },
        { name: "Procedimiento de material no conforme ", operation_id: 58 },
        { name: "Encendido y apagado correcto de la maquinaria ", operation_id: 52 },
        { name: "Comprensión básica de funcionamiento del equipo ", operation_id: 52 },
        { name: "Montaje y desmontaje de guardas de seguridad ", operation_id: 52 },
        { name: "Llenado de papelería (run and rate & traveler)", operation_id: 52 },
        { name: "Interpretación de planos ", operation_id: 52 },
        { name: "Verificación de niveles de criterios de tolerancia ", operation_id: 52 },
        { name: "Tolerancias geométricas (MM & INCH)", operation_id: 52 },
        { name: "Inspección visual (identificación de daños, golpes)", operation_id: 52 },
        { name: "Soldadura ultrasónica ", operation_id: 59 },
        { name: "Ensamble semiautomático ", operation_id: 59 },
        { name: "Prueba de fuga", operation_id: 59 },
        { name: "Capacitación de auditores internos ", operation_id: 56 },
        { name: "Procedimiento de desviación de productos o procesos ", operation_id: 56 },
        { name: "Procedimientos para crear un PPAP", operation_id: 56 },
        { name: "Politica de calidad ", operation_id: 56 },
        { name: "Procedimientos para crear FMEA´S", operation_id: 56 },
        { name: "Sistema de gestión de calidad ", operation_id: 56 },
        { name: "Control de salidas No conforme", operation_id: 56 },
        { name: "Procedimiento de analisis de riesgo inspección de entrada ", operation_id: 56 },
        { name: "Procedimientos para crear contol plan's", operation_id: 56 },
        { name: "Analisis de auditorias internas ", operation_id: 56 },
        { name: "Procedimiento y análisis de riesgo calibración de equipos ", operation_id: 56 },
        { name: "Analisis de riesgos procesos SGC", operation_id: 56 },
        { name: "Control de información documentada ", operation_id: 56 },
        { name: "Procedimiento de inspección y Medición  de producto ", operation_id: 56 },
        { name: "Procedimiento de como generar un IDR", operation_id: 56 },
        { name: "Procedimiento de control de scrap", operation_id: 56 },
        { name: "Procedimiento de identificación y rastreabilidad ", operation_id: 56 },
        { name: "Procedimiento de preservación del producto ", operation_id: 56 },
        { name: "Procedimiento y monitoreo y mediciones de los procesos ", operation_id: 56 },
        { name: "Procedimiento de acciones correctivas ", operation_id: 56 },
        { name: "Blue Belt", operation_id: 56 },
        { name: "Stop Observación ", operation_id: 56 },
        { name: "Green Belt ", operation_id: 56 },
        { name: "RCA", operation_id: 56 },
        { name: "CTQ´s By área ", operation_id: 56 },
        { name: "CURRENT STATE", operation_id: 56 },
        { name: "TARGET ", operation_id: 56 },
        { name: "Set up leak test machine ", operation_id: 53 },
        { name: "Kanban return material ", operation_id: 53 },
        { name: "Scrap process handing ", operation_id: 53 },
        { name: "Nest set up machine ", operation_id: 53 },
        { name: "Dice set up machine ", operation_id: 53 },
        { name: "Dice set up machine return to tool crib ", operation_id: 53 },
        { name: "Recibo de PO material directo ", operation_id: 53 },
        { name: "Recibo de PO material indirecto ", operation_id: 53 },
        { name: "Proceso de recibo e inspección de entrada ", operation_id: 53 },
        { name: "Análisis de riesgo de recibo ", operation_id: 53 },
        { name: "Abastecer material de recibo a almacén ", operation_id: 53 },
        { name: "Revisar transacciones realizadas ", operation_id: 53 },
        { name: "Interpretación/lectura/impresión/surtido de BOM (Kitteo)", operation_id: 53 },
        { name: "Carga y descarga en lína (Cambio de modelo)", operation_id: 53 },
        { name: "Retornos de material ", operation_id: 53 },
        { name: "Reporte de inventarios (Locaciones/Negativod/SOVs)", operation_id: 53 },
        { name: "Manual de proceso de shipping ", operation_id: 53 },
        { name: "Descarga de tráiler en QAD ", operation_id: 53 },
        { name: "Back flush/Revisión de negativos ", operation_id: 53 },
        { name: "Análisis de riesgo de embarques ", operation_id: 53 },
        { name: "Flejado ", operation_id: 53 },
        { name: "Mapeo ", operation_id: 53 },
        { name: "Carga fisica del trailer ", operation_id: 53 },
        { name: "Proceso de embarques", operation_id: 53 },
        { name: "Equipo de protección personal ", operation_id: 53 },
        { name: "Instrucción de trabajo ", operation_id: 53 },
        { name: "Manejo de montacargas ", operation_id: 53 },
        { name: "Manejo de wave ", operation_id: 53 },
        { name: "Blue belt ", operation_id: 53 },
        { name: "5S", operation_id: 53 },
        { name: "Sistema de direcciones ", operation_id: 53 },
        { name: "Realizar transacciones realizadas ", operation_id: 53 },
        { name: "Análisis de riesgo de control de inventario ", operation_id: 53 },
        { name: "APICS básico ", operation_id: 53 },
        { name: "Realizar transacciones en QAD", operation_id: 53 },
        { name: "Llenado de formato de transacciones entre almacenes ", operation_id: 53 },
        { name: "Andon", operation_id: 53 },
        { name: "Sub-ensamble de Oring y seat ", operation_id: 2 },
        { name: "Prueba de fuga", operation_id: 1 },
        { name: "Empaque premier ", operation_id: 61 },
        { name: "Etiquetado premier", operation_id: 61 },
        { name: "Procedimiento de ECN´s", operation_id: 58 },
        { name: "Procedimiento de desviación de producto o proceso ", operation_id: 58 },
        { name: "Procedimiento de introducción de nuevos productos ", operation_id: 58 },
        { name: "Procedimiento de trasferencia de producto o proceso", operation_id: 58 },
        { name: "Procedimiento de control de scrap por muestras de ingeniería ", operation_id: 58 },
        { name: "Procedimiento de FMEA", operation_id: 58 },
        { name: "2-EN-8.2.4-002 Instrucciones de Set up de números de parte en QAD", operation_id: 58 },
        { name: "Análisis de riesgo de proceso de ingeniería ", operation_id: 58 },
        { name: "Análisis de riesgo de proceso de mejora continua ", operation_id: 58 },
        { name: "Certificación en Lean manufacturing ", operation_id: 58 },
        { name: "Certificación de Six sigma ", operation_id: 58 },
        { name: "Certificación de Blue belt", operation_id: 58 },
        { name: "Entrenamiento de 5's", operation_id: 58 },
        { name: "Entrenamiento de standard work ", operation_id: 58 },
        { name: "Entrenamiento de control visual ", operation_id: 58 },
        { name: "Entrenamiento de medición del trabajo ", operation_id: 58 },
        { name: "Entrenamiento de lay out y CAD sofware ", operation_id: 58 },
        { name: "Entrenamiento en CNC machines ", operation_id: 58 },
        { name: "Entrenamiento de preparación de moldes ", operation_id: 58 },
        { name: "Entrenamiento en equipo de machine shop convencional ", operation_id: 58 },
        { name: "Entrenamiento de liderazgo ", operation_id: 58 },
        { name: "Entrenamiento en trabajo en equipo ", operation_id: 58 },
        { name: "Entrenamiento en molde cintifico", operation_id: 58 },
        { name: "Sistema hidráulico e instalaciones ", operation_id: 62 },
        { name: "Torno ", operation_id: 62 },
        { name: "Fresadora ", operation_id: 62 },
        { name: "Rectificadora ", operation_id: 62 },
        { name: "Diagramas eléctricos ", operation_id: 62 },
        { name: "Diagramas electrónicos ", operation_id: 62 },
        { name: "Electrónica ", operation_id: 62 },
        { name: "Sistema neumático e instalaciones ", operation_id: 62 },
        { name: "Programación PLC", operation_id: 62 },
        { name: "Herramientas eléctricas y manuales ", operation_id: 62 },
        { name: "Operar plataformas elevadas ", operation_id: 62 },
        { name: "Operar montacargas ", operation_id: 62 },
        { name: "Equipos de refrigeración ", operation_id: 62 },
        { name: "Equipos de medición ", operation_id: 62 },
        { name: "Uso de equipo de Oxicorte", operation_id: 62 },
        { name: "Uso de IT y medios digitales ", operation_id: 62 },
        { name: "Pintura ", operation_id: 62 },
        { name: "NOM-001-STPS-2008 Limitaciones de área e interpretación de áreas en edificios", operation_id: 62 },
        { name: "NOM-002-STPS-2010 Uso de manejo de extintores y equipo contra incendio ", operation_id: 62 },
        { name: "NOM-002-STPS-2010 Curso de brigadistas prevención y combate de incendio ", operation_id: 62 },
        { name: "NOM-002-STPS-2010 Curso de brigadistas evacuación ", operation_id: 62 },
        { name: "Sistema eléctrico baja tensión ", operation_id: 62 },
        { name: "NOM-002-STPS-2010 Curso de brigadistas primeros auxilios ", operation_id: 62 },
        { name: "NOM-002-STPS-2010 Curso para brigadistas búsqueda y rescate ", operation_id: 62 },
        { name: "NOM-002-STPS-2010 Plan contra emergencias y simulacros ", operation_id: 62 },
        { name: "NOM-002-STPS-2010 Prevención y protección contra incendios ", operation_id: 62 },
        { name: "NOM-004-STPS-1999 Comunicación de riesgos para la operación de maquinaria y equipo ", operation_id: 62 },
        { name: "NOM-004-STPS-1999 Evaluación de riesgos en maquinaria, equipo y procesos. (JHA corporativo)", operation_id: 62 },
        { name: "Sistema eléctrico alta tensión ", operation_id: 62 },
        { name: "NOM-004-STPS-1999 Evaluación de guardas de seguridad y dispositivos de seguridad ", operation_id: 62 },
        { name: "NOM-004-STPS-1999 Conocimiento básico de guardas y dispositivos de seguridad ", operation_id: 62 },
        { name: "NOM-004-STPS-1999 Bloqueo de energía (Lock Out/Tag Out)", operation_id: 62 },
        { name: "Soldadura TIG/MIG", operation_id: 62 },
        { name: "NOM-005-STPS-1999 Control de derrames químicos (Teórico y practico)", operation_id: 62 },
        { name: "NOM-005-STPS-2014 Operación de grúas, polipastos", operation_id: 62 },
        { name: "NOM-006-STPS-2014 Operación de montacargas y pallet Jack", operation_id: 62 },
        { name: "NOM-006-STPS-2014  Levantamiento de objetos y cuidado de la espalda ", operation_id: 62 },
        { name: "NOM-010-STPS-2014 Identificación y clasificación de químicos (Incompatibilidad)", operation_id: 62 },
        { name: "NOM-009-STPS-2011 Equipo suspendido y trabajos en altura ", operation_id: 62 },
        { name: "NOM-010-STPS-1999 Cuidados personales con metales pesados ''Plomo'' y otros químicos peligrosos", operation_id: 62 },
        { name: "Sistema neumático e instalaciones ", operation_id: 62 },
        { name: "Sistema hidráulico e instalaciones ", operation_id: 62 },
        { name: "Sistema eléctrico alta tensión ", operation_id: 62 },
        { name: "Sistema eléctrico baja tensión ", operation_id: 62 },
        { name: "Soldadura TIG/MIG", operation_id: 62 },
        { name: "Torno ", operation_id: 62 },
        { name: "Fresadora ", operation_id: 62 },
        { name: "Rectificadora ", operation_id: 62 },
        { name: "Diagramas eléctricos ", operation_id: 62 },
        { name: "Diagramas electrónicos ", operation_id: 62 },
        { name: "Electrónica ", operation_id: 62 },
        { name: "Programación PLC", operation_id: 62 },
        { name: "Herramientas eléctricas y manuales ", operation_id: 62 },
        { name: "Operar plataformas elevadas ", operation_id: 62 },
        { name: "Operar montacargas ", operation_id: 62 },
        { name: "Equipos de refrigeración ", operation_id: 62 },
        { name: "Equipos de medición ", operation_id: 62 },
        { name: "Uso de equipo de Oxicorte", operation_id: 62 },
        { name: "Uso de IT y medios digitales ", operation_id: 62 },
        { name: "Pintura ", operation_id: 62 },
        { name: "NOM-001-STPS-2008 Limitaciones de área e interpretación de áreas en edificios", operation_id: 62 },
        { name: "NOM-002-STPS-2010 Uso de manejo de extintores y equipo contra incendio ", operation_id: 62 },
        { name: "NOM-002-STPS-2010 Curso de brigadistas prevención y combate de incendio ", operation_id: 62 },
        { name: "NOM-002-STPS-2010 Curso de brigadistas evacuación ", operation_id: 62 },
        { name: "NOM-002-STPS-2010 Curso de brigadistas primeros auxilios ", operation_id: 62 },
        { name: "NOM-002-STPS-2010 Curso para brigadistas búsqueda y rescate ", operation_id: 62 },
        { name: "NOM-002-STPS-2010 Plan contra emergencias y simulacros ", operation_id: 62 },
        { name: "NOM-002-STPS-2010 Prevención y protección contra incendios ", operation_id: 62 },
        { name: "NOM-004-STPS-1999 Comunicación de riesgos para la operación de maquinaria y equipo ", operation_id: 62 },
        { name: "NOM-004-STPS-1999 Evaluación de riesgos en maquinaria, equipo y procesos. (JHA corporativo)", operation_id: 62 },
        { name: "NOM-004-STPS-1999 Evaluación de guardas de seguridad y dispositivos de seguridad ", operation_id: 62 },
        { name: "NOM-004-STPS-1999 Conocimiento básico de guardas y dispositivos de seguridad ", operation_id: 62 },
        { name: "NOM-004-STPS-1999 Bloqueo de energía (Lock Out/Tag Out)", operation_id: 62 },
        { name: "NOM-005-STPS-1999 Control de derrames químicos (Teórico y practico)", operation_id: 62 },
        { name: "NOM-005-STPS-2014 Operación de grúas, polipastos", operation_id: 62 },
        { name: "NOM-006-STPS-2014 Operación de montacargas y pallet Jack", operation_id: 62 },
        { name: "NOM-006-STPS-2014  Levantamiento de objetos y cuidado de la espalda ", operation_id: 62 },
        { name: "NOM-009-STPS-2011 Equipo suspendido y trabajos en altura ", operation_id: 62 },
        { name: "NOM-010-STPS-2014 Identificación y clasificación de químicos (Incompatibilidad)", operation_id: 62 },
        { name: "NOM-010-STPS-1999 Cuidados personales con metales pesados ''Plomo'' y otros químicos peligrosos", operation_id: 62 },
        { name: "Entrenamiento de preparación de moldes ", operation_id: 62 },
        { name: "NOM-027-STPS-2008 Soldadura y corte ", operation_id: 62 },
        { name: "NOM-017-STPS-2008 Uso, revisión, reposición, limpieza, limitaciones y mantenimiento de EPP", operation_id: 62 },
        { name: "NOM-020-STPS-2011 Recipientes sujetos a presión y calderas ", operation_id: 62 },
        { name: "Sistema hidráulico e instalaciones ", operation_id: 63 },
        { name: "Fresadora ", operation_id: 63 },
        { name: "Rectificadora ", operation_id: 63 },
        { name: "Diagramas eléctricos ", operation_id: 63 },
        { name: "Diagramas electrónicos ", operation_id: 63 },
        { name: "Electrónica ", operation_id: 63 },
        { name: "Programación PLC ", operation_id: 63 },
        { name: "Herramientas eléctricas y manuales ", operation_id: 63 },
        { name: "Operar plataformas elevadas ", operation_id: 63 },
        { name: "Operar montacargas ", operation_id: 63 },
        { name: "Equipos de refrigeración ", operation_id: 63 },
        { name: "Equipos para medición ", operation_id: 63 },
        { name: "Uso de equipo de Oxicorte ", operation_id: 63 },
        { name: "Uso de IT y medios digitales ", operation_id: 63 },
        { name: "Pintura ", operation_id: 63 },
        { name: "NOM-001-STPS-2008 Limitaciones de área e interpretación de áreas ", operation_id: 63 },
        { name: "NOM-002-STPS-2010 Uso y manejo de extintores y equipo ", operation_id: 63 },
        { name: "NOM-002-STPS-2010 Curso de brigadistas prevención y combate ", operation_id: 63 },
        { name: "Sistema eléctrico baja tensión ", operation_id: 63 },
        { name: "Sistema neumático e instalaciones ", operation_id: 63 },
        { name: "Sistema eléctrico alta tensión ", operation_id: 63 },
        { name: "Soldadura TIG/MIG ", operation_id: 63 },
        { name: "Torno ", operation_id: 63 },
        { name: "T drill", operation_id: 60 },
        { name: "Bending ", operation_id: 60 },
        { name: "Cutting", operation_id: 60 },
        { name: "Ensamble de o-ring en bonnet", operation_id: 24 },
        { name: "Estampado y ensamble de placa ", operation_id: 24 },
        { name: "Prueba de fuga 7,8 y 9", operation_id: 37 },
        { name: "Prueba de fuga 8 automático ", operation_id: 37 },
        { name: "KIT, empaque y etiquetado de componentes ", operation_id: 36 },
        { name: "Lectura de dibujos ", operation_id: 26 },
        { name: "Estañado soldadura radiant", operation_id: 47 },
        { name: "Limpieza", operation_id: 12 },
        { name: "Ensamble de supercoil", operation_id: 64 },
        { name: "Empaque en maquina ", operation_id: 64 },
        { name: "Remachado conector de manguera ", operation_id: 64 },
        { name: "Corte de manguera ", operation_id: 64 },
        { name: "Empaque de manguera ", operation_id: 64 },
        { name: "Operación heat matrix, corte y empaque ", operation_id: 42 },
        { name: "Operación de custom mat y shower ", operation_id: 42 },
        { name: "Ensamble de control box ", operation_id: 42 },
        { name: "CORE TOOLS", operation_id: 56 }
    ];

    // Inserta todo aunque se repita
    await Skill.bulkCreate(skills);

    console.log(`✅ ${skills.length} operaciones insertadas (incluyendo duplicados)`);
};

module.exports = seedSkills;
